# Copyright (c) Magnon Compute Corporation. All rights reserved.
name: K9s Lint

permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: magnon-enterprise-runners
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1

      - name: Install Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.1.1