# Copyright (c) Magnon Compute Corporation. All rights reserved.
name: K9s Test

permissions:
  contents: read

on:
  workflow_dispatch:
    push:
    branches:
      - master
    tags:
      - rc*
      - v*
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: magnon-enterprise-runners
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1

      - name: Install Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: Run Tests
        run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
